// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZmOlIedqiZ9olWlfjUBsQfi-oj_c4eg0',
    appId: '1:250170568751:web:1951a2e9ae3940781056da',
    messagingSenderId: '250170568751',
    projectId: 'nutrition-app-49530',
    authDomain: 'nutrition-app-49530.firebaseapp.com',
    storageBucket: 'nutrition-app-49530.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXYBtWMVX4Nl3kqg1SRpZP6c14XAQOGhE',
    appId: '1:250170568751:android:83ddab70b3e188cb1056da',
    messagingSenderId: '250170568751',
    projectId: 'nutrition-app-49530',
    storageBucket: 'nutrition-app-49530.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3v-UI_hZ_ePibRf-b9UOBE6xNh1U54fM',
    appId: '1:250170568751:ios:edd9a6d4ece0ff961056da',
    messagingSenderId: '250170568751',
    projectId: 'nutrition-app-49530',
    storageBucket: 'nutrition-app-49530.firebasestorage.app',
    iosBundleId: 'com.example.nutritionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3v-UI_hZ_ePibRf-b9UOBE6xNh1U54fM',
    appId: '1:250170568751:ios:edd9a6d4ece0ff961056da',
    messagingSenderId: '250170568751',
    projectId: 'nutrition-app-49530',
    storageBucket: 'nutrition-app-49530.firebasestorage.app',
    iosBundleId: 'com.example.nutritionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZmOlIedqiZ9olWlfjUBsQfi-oj_c4eg0',
    appId: '1:250170568751:web:8272c3cc82ae9f111056da',
    messagingSenderId: '250170568751',
    projectId: 'nutrition-app-49530',
    authDomain: 'nutrition-app-49530.firebaseapp.com',
    storageBucket: 'nutrition-app-49530.firebasestorage.app',
  );

}